name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main # 每次向 main 分支 push 时触发

# 给整个工作流赋予完全的部署权限，专门解决 id-token 报错
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Files
        run: ./node_modules/.bin/hexo generate

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
